# Generated by Django 6.0.6 on 2026-06-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraGCPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=255)),
                ('camera_id', models.CharField(max_length=100, unique=True)),
                ('top_left_pixel_x', models.FloatField()),
                ('top_left_pixel_y', models.FloatField()),
                ('top_left_lat', models.FloatField()),
                ('top_left_lon', models.FloatField()),
                ('top_right_pixel_x', models.FloatField()),
                ('top_right_pixel_y', models.FloatField()),
                ('top_right_lat', models.FloatField()),
                ('top_right_lon', models.FloatField()),
                ('bottom_right_pixel_x', models.FloatField()),
                ('bottom_right_pixel_y', models.FloatField()),
                ('bottom_right_lat', models.FloatField()),
                ('bottom_right_lon', models.FloatField()),
                ('bottom_left_pixel_x', models.FloatField()),
                ('bottom_left_pixel_y', models.FloatField()),
                ('bottom_left_lat', models.FloatField()),
                ('bottom_left_lon', models.FloatField()),
                ('area_m2', models.FloatField(default=0.0)),
                ('area_hectare', models.FloatField(default=0.0)),
                ('perimeter_m', models.FloatField(default=0.0)),
                ('homography_matrix', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
