# Generated by Django 6.0.6 on 2026-06-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_faceidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('gcp_points', models.JSONField(blank=True, default=dict)),
                ('zones', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
